language: c++
sudo: false
matrix:
  fast_finish: true
  include:
    - name: MaxOs clang
      os: osx
      compiler: clang
      env: CXX="clang++" CC="clang" BUILD_TYPE=release
    - name: Ubuntu 18.04 gcc
      os: linux
      dist: bionic
      compiler: gcc
      env: CXX="g++" CC="gcc" BUILD_TYPE=release
    - name: Ubuntu 18.04 clang
      os: linux
      dist: bionic
      compiler: clang
      env: CXX="clang++" CC="clang" BUILD_TYPE=release

before_install:
  - chmod +x ./install_dependencies.sh && ./install_dependencies.sh

script:
  - pushd estimators && make && popd
  - pushd reconciliation && make && popd